.PHONY: clean
all:
	# cp -rf src/ply bin

	chmod +x src/parser.py
	cp src/parser.py bin/parser
	chmod +x src/Lexer.py
	cp src/Lexer.py bin
	chmod +x src/derivation.py
	cp src/derivation.py bin
	
clean:
	# rm -rf bin/ply

	rm -f bin/*
	rm -f *.html
	rm -f *.txt
